//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitebanhangEx.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Drawing;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            ImagePro = "~/Content/images/default.png";
        }

        public int ProductID { get; set; }
        public string NamePro { get; set; }
        public string DecriptionPro { get; set; }
        public string Category { get; set; }
        public string Handsize { get; set; }
        public string Nentang { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImagePro { get; set; }
        public string KeyWords { get; set; }
        public bool IsSale { get; set; }
        public bool IsHot { get; set; }
        public bool IsNew { get; set; }
        public string ThongSo { get; set; }
        public string Tuongthich { get; set; }
        public string Tronghop { get; set; }
        public string Hotro { get; set; }
        public string Video { get; set; }
        public string Color { get; set; }
        public Nullable<int> Quantity { get; set; }

        public virtual Category Category1 { get; set; }
        public virtual Handsize Handsize1 { get; set; }
        public virtual Nentang Nentang1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
